# Generated by Django 2.2.4 on 2020-07-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granted',
            name='added_date',
            field=models.DateField(blank=True),
        ),
    ]
